packageExtensions:
  "@cucumber/cucumber@*":
    dependencies:
      "@cucumber/pretty-formatter": "*"
      ts-node: "*"
  vite-express@*:
    dependencies:
      express: "*"
      vite: "*"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
